name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          SECSAUCE_USER: ${{ secrets.SECSAUCE_USER }}
          SECSAUCE_PASSWORD: ${{ secrets.SECSAUCE_PASSWORD }}
          CURA_USER: ${{ secrets.CURA_USER }}
          CURA_PASSWORD: ${{ secrets.CURA_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          - name: Verify secret value
  run: |
    if [ "${{ secrets.SECSAUCE_PASSWORD }}" = "secret_sauce" ]; then
      echo "✅ El secret coincide con el valor esperado"
    else
      echo "❌ El secret NO coincide"
    fi
    echo "Longitud del secret: ${#SECRET_VAL}"
  env:
    SECRET_VAL: ${{ secrets.SECSAUCE_PASSWORD }